name: DevopsWF

on: 
    push:
        branches: [main, devops]

jobs:
    Job1: 
        runs-on: ubuntu-latest
        steps:
            - name: Hello World
              run: echo "Hello World!"
    Testing: 
        runs-on: ubuntu-latest
        steps:
            - name: show the repo
              run: ls
            - name: Getting the code to the runner
              uses: actions/checkout@v3
            - name: show the repo
              run: ls
            - name: Testing
              run: |
                echo "Testing started!"
                echo "Testing ..."
                echo "Testing finished!"
    Build: 
        runs-on: ubuntu-latest
        needs: Testing
        steps:
            - name: Getting the code to the runner
              uses: actions/checkout@v3
            - name: Bulding the app
              run: go build -o Prog2025 .
            - name: repo
              run: ls
            - name: Making artifact to export the app
              uses: action/artifact-upload@v4
              with:
                name: Prog2025Artifact
                path: Prog2025
